name: Update README

on:
  push:
    paths:
      - 'gpts/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find the most recently committed file in the gpts directory
        id: findfile
        run: |
          # Find the latest commit affecting any file in the 'gpts/' directory
          LATEST_COMMIT=$(git log -1 --pretty=format:%H -- 'gpts/')

          # Get the name of the file affected in the latest commit
          NEW_FILE=$(git diff-tree --no-commit-id --name-only -r $LATEST_COMMIT | grep '^gpts/' | head -n 1)

          echo "Most recently committed file in 'gpts/' directory:"
          echo "$NEW_FILE"

          if [[ ! -z "$NEW_FILE" ]]; then
            echo "NEW_FILE=$NEW_FILE" >> $GITHUB_ENV
          fi

      - name: Print new file content (for debugging)
        if: env.NEW_FILE
        run: |
          NEW_FILE=${{ env.NEW_FILE }}
          echo "Contents of $NEW_FILE:"
          cat "$NEW_FILE"

      - name: Update README
        if: env.NEW_FILE
        run: |
          NEW_FILE=${{ env.NEW_FILE }}
          CONTENT=$(cat "$NEW_FILE")
          printf "\n\n - $CONTENT" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new content from $NEW_FILE"
          git push
