name: Update README

on:
  push:
    paths:
      - 'gpts/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find newly added file in the latest commit
        id: findfile
        run: |
          # Identify the latest commit hash
          LATEST_COMMIT=$(git rev-parse HEAD)

          # Get the list of added files in the latest commit in 'gpts/' directory
          NEW_FILES=$(git show --pretty="" --name-only --diff-filter=A $LATEST_COMMIT | grep '^gpts/')

          # Debugging: print the list of new files
          echo "Newly added files in the latest commit:"
          echo "$NEW_FILES"

          # Selecting the last newly added file
          NEW_FILE=$(echo "$NEW_FILES" | tail -n 1)

          if [[ ! -z "$NEW_FILE" ]]; then
            echo "Newly added file found: $NEW_FILE"
            echo "NEW_FILE=$NEW_FILE" >> $GITHUB_ENV
          fi

      - name: Print new file content (for debugging)
        if: env.NEW_FILE
        run: |
          NEW_FILE=${{ env.NEW_FILE }}
          echo "Contents of $NEW_FILE:"
          cat "$NEW_FILE"

      - name: Update README
        if: env.NEW_FILE
        run: |
          NEW_FILE=${{ env.NEW_FILE }}
          CONTENT=$(cat "$NEW_FILE")
          printf "\n\n - $CONTENT" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new content from $NEW_FILE"
          git push
