name: Update README

on:
  push:
    paths:
      - 'gpts/**'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find newly added file in the last commit
        id: findfile
        run: |
          # Getting the list of files added in the last commit in the 'gpts/' directory
          NEW_FILES=$(git log -m -1 --name-only --pretty=format: | grep '^gpts/')

          # Debugging: print the list of new files
          echo "Newly added files in the last commit:"
          echo "$NEW_FILES"

          # Selecting the first newly added file (if multiple)
          NEW_FILE=$(echo "$NEW_FILES" | head -n 1)

          if [[ ! -z "$NEW_FILE" ]]; then
            echo "::set-output name=new_file::$NEW_FILE"
          fi

      - name: Print new file content (for debugging)
        if: steps.findfile.outputs.new_file
        run: |
          NEW_FILE="${{ steps.findfile.outputs.new_file }}"
          echo "Contents of $NEW_FILE:"
          cat "$NEW_FILE"

      - name: Update README
        if: steps.findfile.outputs.new_file
        run: |
          NEW_FILE="${{ steps.findfile.outputs.new_file }}"
          CONTENT=$(cat "$NEW_FILE")
          printf "\n - $CONTENT" >> README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with new content from $NEW_FILE"
          git push
